export { default as HomePageSwitcher } from '../frontOffice/containers/HomePageSwitcher'
export { default as DashboardPage } from '../backOffice/containers/DashboardPage'
export { default as CreateArticlePage } from '../backOffice/containers/CreateArticlePage'
export { default as ArticlePage } from '../frontOffice/containers/ArticlePage'
export { default as UpdateArticlePage } from '../backOffice/containers/UpdateArticlePage'
export { default as PreviewArticlePage } from '../backOffice/containers/PreviewArticlePage'
export { default as LoginPage } from '../frontOffice/containers/LoginPage'
export { default as SignUpPage } from '../frontOffice/containers/SignUpPage'
